"""Create bands, venues, and concerts tables

Revision ID: 60f314ae7383
Revises: 1c817528d7d5
Create Date: 2024-09-11 15:35:37.733010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f314ae7383'
down_revision: Union[str, None] = '1c817528d7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
